clc;
clear;
N=1000;
sigma=1.3e-3;
T=9e-3;
h=rand(N,N)*sigma;
delta=0.01;
H=FT2Dc(h);
corr=IFT2Dc(H.*conj(H));
corr=corr*T;
%{
x=-N/2:N/2-1;
x=x*delta;
corr=sigma^2*exp(-x.^2/T);
corr=corr'*corr;
%}
%corr=abs(corr);
%corr=(corr-min(min(corr)))./(max(max(corr))-min(min(corr)));
PSD=abs(FT2Dc(h)).^2/N;
m=IFT2Dc(FT2Dc(h).*(FT2Dc(corr)./PSD).^2);
imshow(abs(m).^2,[])